# Generated by Django 5.0.2 on 2024-02-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
