# Generated by Django 5.0.2 on 2024-02-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0003_remove_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
