# Generated by Django 5.0.2 on 2024-02-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0005_remove_task_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
