# Generated by Django 5.0.2 on 2024-02-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_todo_list', '0006_task_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_id',
        ),
    ]
